# misc taps
brew tap homebrew/binary
brew tap homebrew/dupes
brew tap homebrew/versions
brew tap homebrew/homebrew-php

# setup brew cask
brew install caskroom/cask/brew-cask
brew tap caskroom/cask
brew tap caskroom/fonts
brew tap caskroom/versions

# system
brew cask install xquartz

# shell
brew install zsh
brew install zsh-completions
brew install bash
brew install bash-completion
brew install fasd

# misc cli tools
brew install wget
brew install axel
brew install cowsay
brew install ack
brew install most
brew install mtr
brew install rsync
brew install lftp
brew install p7zip
brew install pwgen
brew install youtube-dl

# main dev stuff
brew install ruby
brew install python
brew install node
brew install git
brew install git-flow
brew install hub
brew cask install chefdk
brew cask install vagrant
brew cask install virtualbox

# php stuff
brew install php55
brew install php55-mcrypt
brew install php55-xdebug
brew install php56
brew install php-version
brew install composer
brew install wp-cli
brew install phpmd
brew install phpunit
brew install behat

# misc dev
brew install httrack
brew install colordiff
brew install ssh-copy-id
brew install mysql
brew install sqlite
brew install diffutils
brew install phantomjs
brew install casperjs
brew install jq
brew install ohcount

# multimedia tools - bins
brew install exiftool
brew install kindlegen
brew install mplayer
brew install ffmpeg
brew install gd
brew install imagemagick
brew install jpegoptim
brew install optipng
brew install webp

# devices
brew install android-platform-tools
brew cask install android-file-transfer
brew cask install horndis
brew cask install razer-synapse

# quicklook
brew cask install betterzipql
brew cask install emin-webpquicklook
brew cask install qlcolorcode
brew cask install qlmarkdown
brew cask install qlprettypatch
brew cask install qlstephen
brew cask install quicklook-csv
brew cask install quicklook-json
brew cask install webp-quicklook

# dev apps
brew cask install iterm2
brew cask install phpstorm
brew cask install sourcetree
brew cask install textmate
brew cask install sequel-pro
brew cask install robomongo
brew cask install mysqlworkbench
brew cask install hipchat
brew cask install cyberduck
brew cask install coda
brew cask install forklift
brew cask install diffmerge

# misc apps
brew cask install alfred
brew cask install flux
brew cask install bartender
brew cask install dropbox
brew cask install rescuetime
brew cask install easyfind
brew cask install appcleaner
brew cask install ccleaner
brew cask install iconping
brew cask install qbittorrent
brew cask install rcdefaultapp
brew cask install skype
brew cask install teamviewer
brew cask install the-unarchiver
brew cask install google-earth
brew cask install wakeonlan
brew cask install grandperspective
brew cask install integrity
brew cask install harvest

# browsers
brew cask install google-chrome
brew cask install google-chrome-beta
brew cask install google-chrome-canary
brew cask install firefox
brew cask install firefox-beta
brew cask install firefoxdeveloperedition

# multimedia apps
brew cask install vlc
brew cask install vox
brew cask install vox-preferences-pane
brew cask install simple-comic
brew cask install handbrake
brew cask install calibre
brew cask install imageoptim
brew cask install mp4tools
brew cask install mpeg-streamclip

# games
brew cask install steam
brew cask install gog-downloader
brew cask install mari0
brew cask install not-tetris

# office stuff
brew cask install libreoffice
brew cask install mou
brew cask install pdfsam